version: "3.11.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma-storage
    volumes:
      - chroma_data:/chroma-storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: ./
    container_name: telegram-bot
    # env_file:
    #   - ./.env
    depends_on:
      redis:
        condition: service_healthy
      chroma:
        condition: service_healthy
    volumes:
      - ./:/app
    command: ["python3.11", "./app/app.py"]

volumes:
  redis_data:
  chroma_data:
